steps:
  build:
    image: nixpkgs/nix
    commands:
    - nix --extra-experimental-features nix-command --extra-experimental-features flakes flake check
    - nix --extra-experimental-features nix-command --extra-experimental-features flakes build .
